apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: webapp-fwdauth
  namespace: webapp
spec:
  forwardAuth:
    address: http://opa-shim-server.opa:8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: red-stripprefix
  namespace: webapp
spec:
  stripPrefix:
    prefixes:
      - /foo/bar
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: red-chain
  namespace: webapp
  labels:
    app: red-server
spec:
  chain:
    middlewares:
    - name: webapp-fwdauth
    - name: red-stripprefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: green-stripprefix
  namespace: webapp
spec:
  stripPrefix:
    prefixes:
      - /foo
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: green-chain
  namespace: webapp
  labels:
    app: green-server
spec:
  chain:
    middlewares:
    - name: webapp-fwdauth
    - name: green-stripprefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: blue-stripprefix
  namespace: webapp
spec:
  stripPrefix:
    prefixes:
      - /bar
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: blue-chain
  namespace: webapp
  labels:
    app: blue-server
spec:
  chain:
    middlewares:
    - name: webapp-fwdauth
    - name: blue-stripprefix
