apiVersion: v1
kind: Service
metadata:
  name: opa-shim-server
  namespace: opa
  labels:
    app: opa-shim-server
spec:
  selector:
    app: opa-shim-server
  ports:
  - name: test-port
    protocol: TCP
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-shim-server
  namespace: opa
  labels:
    app: opa-shim-server
spec:
  selector:
    matchLabels:
      app: opa-shim-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: opa-shim-server
    spec:
      containers:
      - name: opa-shim-server
        image: pfcurtis/opa-shim-server:7fb8b66
        ports:
        - name: test-port
          containerPort: 8080
        env:
        - name: "OPA_URL"
          value: "http://opa.opa:8181/v1/data/example"
